@startuml
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/v1.0.1/theme.puml
hide circle
skinparam {
    classAttributeIconSize 0
    packageStyle rectangle
    backgroundColor transparent
}  

class FeldGenerator {
    - int anzahlZeilen
    - int anzahlSpalten
    - FilledShape[] feld
    + void generiereFeld(int zeilen, int spalten)
    + void setzeFarbe(String farbe, int x, int y)
}

class FeldGenerator2D {
    - FilledShape[][] feld
    + void generiereFeld(int anzahlZeilen, int anzahlSpalten)
    + FilledShape[] spalteErzeugen(int anzahlZeilen, int x)
    + void setzeFarbe(String farbe, int x, int y)
}

class Main {
    {static} + void main()
}

FeldGenerator <|-- FeldGenerator2D

@enduml